{
        'Acrobacia' : 'Des',
        'Artesanato': 'Des',
        'Misticismo' : 'Eru',
        'Atletismo' : 'Con',
        'Atuação' : 'Per',
        'Culinária' : 'Eru',
        'Cultivo' : 'Intu',
        'Empatia' : 'Intu',
        'Fé' : 'Intu',
        'Folego' : 'Con',
        'Furtividade' : 'Des',
        'História' : 'Eru',
        'Imunidade' : 'Con',
        'Intimidação' : 'Per',
        'Levantamento_de_peso' : 'For',
        'Liderança' : 'Per',
        'Medicina' : 'Eru',
        'Musicalidade' : 'Per',
        'Natureza' : 'Eru',
        'Negociação' : 'Per',
        'Percepção' : 'Intu',
        'Trato_com_animais' : 'Intu'
    }